### ISSUE TITLE
Configuration does not set vcloud config correctly

### ISSUE THREAD

**Issue by surfer190** [StackStorm-Exchange/stackstorm-vcd#9]
Steps to reproduce:

1. Install the pack `st2 pack install vcd`

2. Configure the pack `st2 pack config vcd` and enter config

3. See the following results

```
defaults:
  org:
    Settings:
      ...
vcloud: {}
vclouds:
  host: xxx
  passwd: xxx
  ssl_verify: true
  user: xxx
```

Then run `st2 action execute vcd.get_org_ids`

```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/vcd/actions/get_org_ids.py", line 21, in run
    self.set_connection(vcloud)
  File "/opt/stackstorm/packs/vcd/actions/lib/vcd.py", line 43, in set_connection
    self.vcd_host = self.config['vcloud'][vcloud]['host']
KeyError: u'xxx'
```

**Expected Results**

The `vcloud` dictionary is setup correctly during configuration.

```
vcloud: {
  'default': {
    'host': 'xxx',
    'passwd': 'xxx',
    'ssl_verify': True,
    'user': 'xxx'
  }
}
```

**Comment by nmaludy** [comment]
`st2 pack config` is not supported for this pack because it uses complex nested configuration. See this issue on the main repo; https://github.com/StackStorm/st2/issues/3276

You'll have to edit `/opt/stackstorm/configs/vcd.yaml` manually to enter the proper syntax. See the example config for what it should look like: https://github.com/StackStorm-Exchange/stackstorm-vcd/blob/master/vcd.yaml.example
